get_data:
  name: Получить данные
  description: "Получить данные об устройствах и командах ИК-пульта"

learn_code:
  name: Обучение ИК-коду
  description: "Перевести ИК-пульт в режим обучения и сохранить код"
  fields:
    device:
      name: Устройство
      description: Имя устройства
      required: true
      selector:
        text:
    button:
      name: Кнопка
      description: Имя кнопки
      required: true
      selector:
        text:

send_code:
  name: Отправить ИК-код
  description: "Отправить ИК-код вручную"
  fields:
    code:
      name: Код
      description: ИК-код для отправки
      required: true
      selector:
        text:

send_command:
  name: Отправить команду
  description: "Отправить команду для выбранного устройства"
  fields:
    device:
      name: Устройство
      description: Имя устройства
      required: true
      selector:
        text:
    command:
      name: Команда
      description: Команда для отправки
      required: true
      selector:
        text:

add_device:
  name: Добавить устройство
  description: "Добавить новое устройство в список устройств ИК-пульта"
  fields:
    name:
      name: Имя устройства
      description: Имя нового устройства
      required: true
      selector:
        text: